SENDGRID_USERNAME:
SENDGRID_PASSWORD:

# development
# BT_ENVIRONMENT='sandbox'
# BT_MERCHANT_ID='MERCHANT_ID'
# BT_PUBLIC_KEY='PUBLIC_KEY'
# BT_PRIVATE_KEY='PRIVATE_KEY'

# production
BT_ENVIRONMENT='production'
BT_MERCHANT_ID='MERCHANT_ID'
BT_PUBLIC_KEY='PUBLIC_KEY'
BT_PRIVATE_KEY='PRIVATE_KEY'